(() => {
'use strict';
const $=s=>document.querySelector(s), main=$('#main');
const {scenes}=window.NING_DATA,{lessons,mba}=window.NING_CURRICULUM;
const allPhrases=scenes.flatMap(s=>s.phrases.map(p=>({...p,scene:s.id}))), phraseMap=new Map(allPhrases.map(p=>[p.id,p]));
const KEY='ning-learning-v1', START='2026-09-23', validDay=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s+'T12:00:00'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dayShift=(s,n)=>{const d=new Date(s+'T12:00:00');d.setDate(d.getDate()+n);return localDate(d)};
const dayIndex=s=>Math.round((Date.parse(s+'T12:00:00Z')-Date.parse(START+'T12:00:00Z'))/86400000);
let today=localDate(),selectedDate=today,storageOK=true,state={version:1,records:{}},filter={q:'',category:'',date:'',favorite:false,unmastered:false},revealed=new Set(),toastTimeout,timerHandle,installEvent,voices=[],currentUtterance=null;
try{const raw=localStorage.getItem(KEY);if(raw){const s=JSON.parse(raw);if(s.version!==1||!s.records||typeof s.records!=='object'||Array.isArray(s.records))throw Error('bad schema');state=s;}}catch(e){storageOK=false;}
const record=k=>state.records[k],get=(k,fallback=false)=>record(k)?.value??fallback;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;toast('无法持久保存，请导出进度备份。');}storageStatus();}
function put(k,value){state.records[k]={value,updated:new Date().toISOString()};save();}
function toast(s){const el=$('#toast');el.textContent=s;el.style.display='block';clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.style.display='none',3000)}
function storageStatus(){const e=$('#storage-status');if(e)e.textContent=storageOK?'本机保存已启用 · 不自动跨设备同步':'浏览器存储不可用或原数据无法读取：本次进度请导出备份。';}
const idx=(n,len)=>((n%len)+len)%len;
const lessonOrder=['de-01','de-02','de-03','de-04','de-05','de-06','de-07','de-08','de-09','de-10','de-11'], mbaOrder=['mba-01','mba-02','mba-03','mba-04','mba-05','mba-06','mba-07'];
const plan=d=>({lesson:lessons.find(l=>l.id===lessonOrder[idx(dayIndex(d),lessonOrder.length)]),article:mba.find(a=>a.id===mbaOrder[idx(dayIndex(d),mbaOrder.length)])});
const stepKey=(d,id,step)=>`step|${d}|${id}|${step}`;
const stepsFor=id=>id.startsWith('de-')?['input','vocab','reading','quiz','review']:['input','vocab','framework','thinking'];
const complete=(d,id)=>stepsFor(id).every(s=>get(stepKey(d,id,s))===true);
const reviewed=(d,scene)=>scenes.find(s=>s.id===scene).phrases.filter(p=>get(`practice|${d}|${p.id}`)).length;
const taskProgress=d=>{const p=plan(d);return [reviewed(d,p.lesson.scene)>=5,complete(d,p.lesson.id),complete(d,p.article.id)]};
const activeDays=()=>new Set(Object.keys(state.records).filter(k=>/^(practice|step)\|/.test(k)&&get(k)===true).map(k=>k.split('|')[1]));
const masteredCount=()=>allPhrases.filter(p=>get('mastered|'+p.id)).length;
const favoriteCount=()=>allPhrases.filter(p=>get('favorite|'+p.id)).length;
const duePhrases=()=>allPhrases.filter(p=>(get('favorite|'+p.id)&&!get(`practice|${today}|${p.id}`))||get('due|'+p.id,'9999')<=today);
function heading(eyebrow,title,desc='',right=''){return `<div class="heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1>${desc?`<p class="muted">${desc}</p>`:''}</div>${right}</div>`}
const tag=s=>`<span class="tag">${esc(s)}</span>`;
function dateControl(){return `<label class="date-control">学习日期 <input aria-label="学习日期" id="study-date" type="date" min="${START}" max="${today}" value="${selectedDate}"></label>`}
const dayFormat=d=>new Date(d+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'});
const activityWeek=()=>Array.from({length:7},(_,i)=>{const d=dayShift(today,i-6);return `<div class="day"><span>${new Date(d+'T12:00:00').toLocaleDateString('en',{weekday:'short'})}</span><i class="${activeDays().has(d)?'done':''}">${activeDays().has(d)?'✓':d.slice(-2)}</i></div>`}).join('');
function latestScenes(){const featured=(window.NING_DATA.featured||[]).map(id=>scenes.find(s=>s.id===id)).filter(Boolean);return featured.length?`<section class="panel latest"><div class="progress-head"><h2>新场景 · ${esc(window.NING_DATA.updated)}</h2>${tag('可直接练习')}</div><div class="latest-grid">${featured.map(s=>`<a class="latest-card" data-featured href="#scenes/${s.id}"><strong>${esc(s.title)}</strong><small>${esc(s.zh)}</small><span>${s.phrases.length} 句 · 开始 →</span></a>`).join('')}</div><p class="status-line">先练你的提问，再听对方可能的回答；每个场景挑 5 句开口自测。</p></section>`:'';}
function home(){selectedDate=today;const p=plan(today),tasks=taskProgress(today),n=tasks.filter(Boolean).length,s=scenes.find(s=>s.id===p.lesson.scene),fav=favoriteCount();
main.innerHTML=heading('YOUR DAILY LEARNING SPACE','Heute. Today. 今天。','Ning，从今天的一次开口开始。',`<span class="date-chip">${dayFormat(today)}</span>`)+
latestScenes()+`<div class="dashboard-grid"><section class="focus"><span class="eyebrow">TODAY’S FOCUS · 场景德语</span><h2>${s.id==='parkour'?'Ready for Parkour?':esc(s.title)}</h2><p>${esc(p.lesson.goal)}</p><div class="focus-bottom"><a class="button" href="#scenes/${s.id}">开始今天的练习 →</a><span class="tag">${p.lesson.level} · 5 句起</span></div></section><section class="panel"><div class="progress-head"><h2>今日进度</h2>${tag(n===3?'DONE FOR TODAY':'ONE STEP AT A TIME')}</div><div class="big-number">${n} <small>/ 3 项任务</small></div><div class="bar" role="progressbar" aria-label="今日任务" aria-valuemin="0" aria-valuemax="3" aria-valuenow="${n}"><span style="width:${n/3*100}%"></span></div><div class="stats"><div><strong>${masteredCount()}</strong><small>已掌握句子</small></div><div><strong>${fav}</strong><small>收藏难句</small></div><div><strong>${activeDays().size}</strong><small>学习天数</small></div></div></section></div>
<div class="section-title"><h2>你的学习库</h2><span>Three ways to grow</span></div><div class="modules"><a href="#scenes" class="module"><span class="module-symbol">DE</span><h3>场景德语</h3><p>真实生活，随时开口。</p><div class="module-footer"><span>${scenes.length} 场景 · ${allPhrases.length} 句</span><span>↗</span></div></a><a href="#deutsch" class="module"><span class="module-symbol">A²</span><h3>A1–A2 Deutsch</h3><p>输入、朗读、测试、复习。</p><div class="module-footer"><span>${lessons.length} 单元 · 每日 25–40 min</span><span>↗</span></div></a><a href="#mba" class="module"><span class="module-symbol">EN</span><h3>MBA Daily</h3><p>用英语理解商业。</p><div class="module-footer"><span>${mba.length} 篇精读 · 每日 15 min</span><span>↗</span></div></a></div>
<div class="section-title"><h2>今天的学习清单</h2><span>${n}/3 completed</span></div><div class="dashboard-grid"><section class="panel">${[
['场景热身 · '+s.zh,`${Math.min(reviewed(today,s.id),5)}/5 句已自测 · 约 5 min`,'scenes/'+s.id],
['A1–A2 · '+p.lesson.title.split(' · ')[0],'输入 + 15–30 分钟朗读 + mini test','deutsch'],
['MBA · '+p.article.title,'一份输入 + 五个词 + 一段思考','mba']
].map((t,i)=>`<div class="task-row"><span class="check ${tasks[i]?'done':''}">${tasks[i]?'✓':i+1}</span><div class="task-body"><strong>${esc(t[0])}</strong><small>${esc(t[1])}</small></div><a href="#${t[2]}">${tasks[i]?'回顾':'开始'} →</a></div>`).join('')}</section><section class="panel"><div class="progress-head"><h2>最近 7 天</h2><a href="#history" class="source">记录 ↗</a></div><div class="week">${activityWeek()}</div><p class="status-line">每次开口和完成任务，都会留下记录。</p><a class="button secondary" href="#review">复习队列 · ${duePhrases().length} 句</a></section></div><p class="footnote">进度保存在当前设备 · 每日自动轮换学习单元，完成后进入巩固复习。<button class="text-button" data-action="settings">朗读、备份与安装</button></p>`;
}
function sceneList(){main.innerHTML=heading('GERMAN ALLTAG','场景德语','把生活里遇到的每一句，变成下次能说出的那一句。')+`<div class="filters"><input type="search" id="search" aria-label="搜索德语或英文" placeholder="搜索场景、德语或英文…" value="${esc(filter.q)}"><select id="category" aria-label="场景类型"><option value="">全部场景类型</option>${[...new Set(scenes.map(s=>s.category))].map(c=>`<option ${c===filter.category?'selected':''}>${c}</option>`).join('')}</select><select id="scene-date" aria-label="场景日期"><option value="">全部内容日期</option>${[...new Set(scenes.flatMap(s=>[s.date,s.updated].filter(Boolean)))].sort().reverse().map(d=>`<option ${d===filter.date?'selected':''}>${d}</option>`).join('')}</select></div><div class="filters"><label><input type="checkbox" id="fav-filter" ${filter.favorite?'checked':''}>只看收藏</label><label><input type="checkbox" id="unmastered-filter" ${filter.unmastered?'checked':''}>未掌握</label><a href="#review" class="button secondary">复习难句 →</a></div><p class="status-line" id="result-count"></p><div class="scene-grid" id="scene-results"></div><p class="footnote">日期包含内容新增／更新日期及历史对话日期；场景对话是练习示例，价格、路线及办事要求以现场信息为准。</p>`;updateSceneResults();}
function matches(p,s){return (!filter.favorite||get('favorite|'+p.id))&&(!filter.unmastered||!get('mastered|'+p.id))&&(!filter.q||`${s.title} ${s.zh} ${p.de} ${p.en}`.toLowerCase().includes(filter.q.toLowerCase()));}
function updateSceneResults(){const list=[...scenes].sort((a,b)=>(b.updated||b.date).localeCompare(a.updated||a.date)).filter(s=>(!filter.category||s.category===filter.category)&&(!filter.date||s.date===filter.date||s.updated===filter.date)).map(s=>({...s,matched:s.phrases.filter(p=>matches(p,s))})).filter(s=>s.matched.length);$('#result-count').textContent=`${list.length} 个场景 · ${list.reduce((n,s)=>n+s.matched.length,0)} 句符合筛选`;$('#scene-results').innerHTML=list.map(s=>{const n=s.phrases.filter(p=>get('mastered|'+p.id)).length;return `<a href="#scenes/${s.id}" class="scene-card"><div class="meta"><span>${s.category}</span><span>${s.updated?"更新 "+s.updated:s.date}</span></div><h2>${esc(s.title)}</h2><p>${esc(s.zh)}</p><div class="bar"><span style="width:${n/s.phrases.length*100}%"></span></div><div class="meta"><span>${n}/${s.phrases.length} 已掌握</span><span>${s.matched.length} 句可练习 →</span></div></a>`}).join('')||'<div class="empty panel"><h2>没有匹配的场景</h2><p>换一个关键词或清除筛选。</p><button data-action="clear-filters">清除筛选</button></div>';}
function phraseHTML(p){const only=get('pref|germanOnly'),fav=get('favorite|'+p.id),master=get('mastered|'+p.id),practiced=get(`practice|${today}|${p.id}`);return `<article class="phrase" data-phrase="${p.id}">${p.speaker?`<span class="speaker">${esc(p.speaker)}</span>`:""}<p class="phrase-de" lang="de" translate="no">${esc(p.de)}</p><p class="phrase-en" lang="en" ${only&&!revealed.has(p.id)?'hidden':''}>${esc(p.en)}</p><div class="phrase-controls">${only?`<button data-action="reveal" data-id="${p.id}" aria-expanded="${revealed.has(p.id)}">${revealed.has(p.id)?'隐藏英文':'揭晓英文'}</button>`:''}<button data-action="speak" data-id="${p.id}" aria-label="朗读 ${esc(p.de)}">▷ 朗读</button><button data-action="favorite" data-id="${p.id}" class="${fav?'selected':''}" aria-pressed="${fav}">${fav?'★ 已收藏':'☆ 收藏'}</button><button data-action="master" data-id="${p.id}" class="${master?'selected':''}" aria-pressed="${master}">${master?'✓ 已掌握':'标记掌握'}</button><button data-action="practice" data-id="${p.id}" class="${practiced?'selected':''}" aria-pressed="${practiced}">${practiced?'✓ 今日已自测':'已开口自测'}</button></div></article>`}
function modeControls(){return `<div class="filters sticky-controls"><label><input type="checkbox" id="german-only" ${get('pref|germanOnly')?'checked':''}> German-only 自测</label><button class="text-button" data-action="settings" data-voice-status>德语声音设置</button><button class="text-button" data-action="stop-speech">停止朗读</button></div>`}
function sceneDetail(id){const s=scenes.find(s=>s.id===id);if(!s)return notFound();let list=s.phrases.filter(p=>matches(p,s));main.innerHTML=`<a class="back" href="#scenes">← 场景库</a>`+heading(s.category.toUpperCase()+' · '+(s.updated?'更新 '+s.updated:s.date),esc(s.title),esc(s.zh))+modeControls()+`<label class="section-jump">跳到环节 <select id="scene-section"><option value="">选择环节…</option>${[...new Set(list.map(p=>p.section))].map((section,i)=>`<option value="section-${i}">${esc(section)}</option>`).join('')}</select></label><div class="status-line">${list.length} 句 · 本场景今日已自测 <span data-scene-practiced="${s.id}">${reviewed(today,s.id)}</span> 句${list.length!==s.phrases.length?' · 已应用场景库筛选':''}</div><section class="panel" id="phrases">${list.map((p,i)=>(i===0||p.section!==list[i-1].section?`<h2 class="section-marker" id="section-${[...new Set(list.map(x=>x.section))].indexOf(p.section)}" tabindex="-1">${esc(p.section)}</h2>`:'')+phraseHTML(p)).join('')||'<p>当前筛选下没有句子。</p><button data-action="clear-detail-filters">显示全部句子</button>'}</section><details class="panel"><summary>场景笔记与词汇链</summary><div class="reference">${formatReference(s.reference)}</div>${(s.sources||[]).map(x=>`<p class="source"><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title)} ↗</a></p>`).join('')}</details>`;}
function formatReference(raw){return esc(raw).replace(/^#{1,5}\s+(.+)$/gm,'<h3>$1</h3>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/^---$/gm,'<hr>');}
function review(){const list=duePhrases();main.innerHTML=heading('REVIEW & REMEMBER','复习队列',`收藏难句与到期句子 · ${list.length} 句`)+modeControls()+`<section class="panel">${list.length?list.slice(0,20).map(p=>`<a class="source" href="#scenes/${p.scene}">${esc(scenes.find(s=>s.id===p.scene).title)}</a>`+phraseHTML(p)).join(''):'<div class="empty"><h2>复习队列已清空</h2><p>收藏难句后会出现在这里。已自测的句子会在次日或 7 天后回到队列。</p><a href="#scenes" class="button primary">去场景库练习</a></div>'}</section>${list.length>20?'<p class="muted">本轮显示前 20 句，完成后点击下一轮。</p>':''}<button data-action="refresh-review">更新复习队列</button>`;}
const check=(d,id,s,label)=>`<label class="step-check"><input type="checkbox" data-step="${s}" data-unit="${id}" data-date="${d}" ${get(stepKey(d,id,s))?'checked':''}>${label}</label>`;
const vocabHTML=words=>`<div class="vocab">${words.map(([w,e])=>`<div><strong>${esc(w)}</strong><small>${esc(e)}</small></div>`).join('')}</div>`;
function unitProgress(d,id){const n=stepsFor(id).filter(s=>get(stepKey(d,id,s))).length;return `<span class="tag" data-unit-progress="${id}">${n}/${stepsFor(id).length} 已完成</span>`}
function refreshUnitProgress(d,id){document.querySelectorAll(`[data-unit-progress="${id}"]`).forEach(el=>{el.outerHTML=unitProgress(d,id)});}
function deutsch(id){const d=selectedDate,l=lessons.find(l=>l.id===id)||plan(d).lesson;const qi=get(`quiz|${d}|${l.id}`,null);const cycle=Math.floor(Math.max(0,dayIndex(d))/lessons.length)+1;
main.innerHTML=heading('A1–A2 DEUTSCH · '+l.level,esc(l.title),`${esc(l.goal)} · 第 ${cycle} 轮${cycle>1?'巩固复习':''}`,dateControl())+`<div class="section-title"><span>新增学习单元 · 25–40 min</span>${unitProgress(d,l.id)}</div><section class="panel"><span class="step">01 / INPUT · 3 MIN</span><h2>先读懂，再开口</h2><p class="reading" lang="de">${esc(l.input)}</p><div class="actions"><button data-action="speak-unit" data-id="${l.id}">▷ 听德语朗读</button><button data-action="stop-speech">停止朗读</button><button data-action="settings" data-voice-status>德语声音设置</button></div><details><summary>查看 English 对照</summary><p lang="en" class="muted">${esc(l.translation)}</p></details>${check(d,l.id,'input','我已读懂这段输入')}</section><section class="panel"><span class="step">02 / VOCABULARY & PATTERNS · 4 MIN</span>${vocabHTML(l.vocab)}<h3>今天的句型</h3><p>${esc(l.pattern)}</p>${check(d,l.id,'vocab','我能用这些词造句')}</section><section class="panel"><span class="step">03 / ALOUD READING · 15–30 MIN</span><h2>让嘴巴先熟悉德语</h2><ol>${l.prompts.map(p=>`<li>${esc(p)}</li>`).join('')}</ol><p class="muted source">每一步约 5 分钟：慢读 → 替换 → 脱稿。可用下方场景扩展对话。</p><div class="actions"><label>时长 <select id="timer-duration" aria-label="朗读时长"><option value="15">15 min</option><option value="20">20 min</option><option value="30">30 min</option></select></label><span class="timer" id="timer-display">15:00</span><button data-action="timer-toggle" data-id="${l.id}">开始计时</button><button data-action="timer-reset" data-id="${l.id}">重置</button></div><p class="status-line">计时结束后手动确认完成；也可记录线下朗读。</p>${check(d,l.id,'reading','我已完成 15–30 分钟朗读')}</section><section class="panel"><span class="step">04 / MINI TEST · 3 MIN</span><h2>合上课文，试试看</h2><form class="quiz" id="quiz" data-unit="${l.id}" data-date="${d}">${l.quiz.map(([q,answers],i)=>`<fieldset><legend>${i+1}. ${esc(q)}</legend>${answers.map((a,j)=>`<label><input type="radio" required name="q${i}" value="${j}" ${qi?.answers?.[i]===j?'checked':''}>${esc(a)}</label>`).join('')}</fieldset>`).join('')}<button class="primary" type="submit">检查答案</button><div id="quiz-result" aria-live="polite">${qi?quizResult(l,qi):''}</div></form></section><section class="panel"><span class="step">05 / REVIEW · 3 MIN</span><h2>带回真实生活</h2><p>${esc(l.review)}</p><a class="button secondary" href="#scenes/${l.scene}">打开对应场景 →</a>${check(d,l.id,'review','我已完成复习')}</section><section class="panel"><h2>学习笔记</h2><textarea class="note-input" data-note="${l.id}" data-date="${d}" placeholder="今天在哪儿用了德语？还有什么没听懂？">${esc(get(`note|${d}|${l.id}`,''))}</textarea><p class="status-line" id="note-status">输入后自动保存到 ${d}</p></section><details class="panel"><summary>全部 ${lessons.length} 个学习单元</summary>${lessons.map((x,i)=>`<a class="archive-item" href="#deutsch/${x.id}"><div><strong>${String(i+1).padStart(2,'0')} · ${esc(x.title)}</strong><small>${x.level} · ${esc(x.goal)}</small></div>${unitProgress(d,x.id)}</a>`).join('')}</details>`;updateTimer(l.id);}
function quizResult(l,q){return `<div class="result"><strong>${q.score}/3 正确${q.score===3?' · Mini test 已完成':' · 修改后再试一次'}</strong>${l.quiz.map((item,i)=>`<p>${q.answers[i]===item[2]?'✓':'○'} ${i+1}. ${esc(item[3])}</p>`).join('')}</div>`}
function mbaPage(id){const d=selectedDate,a=mba.find(a=>a.id===id)||plan(d).article,cycle=Math.floor(Math.max(0,dayIndex(d))/mba.length)+1;main.innerHTML=heading('MBA DAILY · '+a.topic.toUpperCase(),esc(a.title),'Business English · 15 min · 第 '+cycle+' 轮'+(cycle>1?'复习':''),dateControl())+`<div class="section-title"><span>学习安排 ${d} · ${a.sourceDate}</span>${unitProgress(d,a.id)}</div><section class="panel"><span class="step">01 / SELECTED INPUT</span><h2>Read with a question</h2><p lang="en">${esc(a.brief)}</p><p class="source"><a href="${a.url}" target="_blank" rel="noopener noreferrer">${esc(a.source)} ↗</a></p><p class="status-line">经典商业材料，非当日新闻；原文需联网阅读。下方原创练习可离线使用。</p><h3>Summary</h3><p lang="en"><strong>${esc(a.summary)}</strong></p><h3>Apply it to everyday life</h3><p class="reading" lang="en">${esc(a.body)}</p>${check(d,a.id,'input','已完成阅读并能复述 summary')}</section><section class="panel"><span class="step">02 / BUSINESS VOCABULARY</span>${vocabHTML(a.vocab)}<p class="muted source">挑 2 个词，用它们描述身边的一家店。</p>${check(d,a.id,'vocab','已用至少两个词造句')}</section><section class="panel"><span class="step">03 / CONCEPT & FRAMEWORK</span><h2>${esc(a.topic)}</h2><p>${esc(a.framework)}</p>${check(d,a.id,'framework','我能把这个框架用于一个例子')}</section><section class="panel"><span class="step">04 / THINKING QUESTION</span><h2>Your take.</h2><p lang="en">${esc(a.question)}</p><p class="muted source" lang="en">${esc(a.starter)}</p><textarea class="note-input" data-note="${a.id}" data-date="${d}" placeholder="Write your answer in English…">${esc(get(`note|${d}|${a.id}`,''))}</textarea><p class="status-line" id="note-status">自动保存 · ${get(`note|${d}|${a.id}`,'').trim().split(/\s+/).filter(Boolean).length} words</p>${check(d,a.id,'thinking','已完成思考与英文输出')}</section><details class="panel"><summary>7 篇精读与学习日期归档</summary><p class="muted source">学习日期是你的安排日期，不是文章发布日期。完成本轮后，每天继续复习一篇。</p>${mba.map((x,i)=>`<a class="archive-item" href="#mba/${x.id}"><div><strong>${String(i+1).padStart(2,'0')} · ${esc(x.title)}</strong><small>${esc(x.topic)}</small></div>${unitProgress(d,x.id)}</a>`).join('')}<a href="#history" class="button secondary">查看按日期保存的笔记 →</a></details>`;}
function history(){const days=[...new Set(Object.keys(state.records).filter(k=>/^(step|practice|note|quiz)\|/.test(k)).map(k=>k.split('|')[1]).filter(validDay))].sort().reverse();main.innerHTML=heading('YOUR LEARNING JOURNAL','学习记录','每一次输入、输出和练习，按日期留存。')+`<section class="panel">${days.length?days.map(d=>{const p=plan(d),n=taskProgress(d).filter(Boolean).length;return `<details><summary>${d} · ${n}/3 项计划任务 · ${Object.keys(state.records).filter(k=>k.startsWith('practice|'+d+'|')&&get(k)).length} 句自测</summary><div class="actions"><button data-action="open-day" data-date="${d}" data-module="deutsch">德语任务</button><button data-action="open-day" data-date="${d}" data-module="mba">MBA Daily</button></div>${Object.keys(state.records).filter(k=>k.startsWith('note|'+d+'|')&&get(k)).map(k=>{const id=k.split('|')[2],unit=[...lessons,...mba].find(u=>u.id===id);return `<h3>${esc(unit?.title||id)}</h3><p style="white-space:pre-wrap">${esc(get(k))}</p>`}).join('')}</details>`}).join(''):'<div class="empty"><h2>你的第一条记录，从今天开始</h2><p>完成一条自测或一项任务后，这里就会留下记录。</p><a href="#today" class="button primary">去今日学习</a></div>'}</section>`;}
function notFound(){main.innerHTML='<div class="empty"><h1>没有找到这个单元</h1><a href="#today">返回 Today</a></div>'}
function render(){clearInterval(timerHandle);const [route,id]=location.hash.slice(1).split('/');document.querySelectorAll('aside a').forEach(a=>{const r=a.hash.slice(1);const active=r===(route||'today');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(!route||route==='today')home();else if(route==='scenes')id?sceneDetail(id):sceneList();else if(route==='deutsch')deutsch(id);else if(route==='mba')mbaPage(id);else if(route==='review')review();else if(route==='history')history();else notFound();refreshVoiceSettings();document.title=`${main.querySelector('h1')?.textContent||'Today'} · Ning Learning`;}
function refreshPhrase(id){const p=phraseMap.get(id),el=main.querySelector(`[data-phrase="${id}"]`);if(el)el.outerHTML=phraseHTML(p);}
function markPractice(id){if(!phraseMap.has(id))throw Error('未知句子');put(`practice|${today}|${id}`,true);put('due|'+id,dayShift(today,get('mastered|'+id)?7:1));refreshPhrase(id);document.querySelectorAll('[data-scene-practiced]').forEach(el=>el.textContent=reviewed(today,el.dataset.scenePracticed));}
const speechSupported='speechSynthesis' in window && typeof SpeechSynthesisUtterance!=='undefined';
const isGermanVoice=v=>/^de(?:[-_]|$)/i.test(v?.lang||'');
const voiceKey=v=>`${v.lang}|${v.voiceURI||v.name}`;
const voiceRank=v=>{const lang=(v.lang||'').toLowerCase().replace('_','-');return (lang==='de-de'?100:lang==='de-at'?80:lang==='de-ch'?70:60)+(v.localService?5:0);};
function germanVoices(){return voices.filter(isGermanVoice).filter(v=>navigator.onLine||v.localService);}
function preferredGermanVoice(){const saved=get('pref|deVoice',''),list=germanVoices();return list.find(v=>voiceKey(v)===saved||(v.voiceURI||v.name)===saved)||list[0]||null;}
function refreshVoiceSettings(){
  const select=$('#voice-select'),status=$('#voice-status');if(!select)return;
  const list=germanVoices(),voice=preferredGermanVoice(),saved=get('pref|deVoice','');
  select.innerHTML='<option value="">自动选择德语（优先德国）</option>'+list.map(v=>`<option value="${esc(voiceKey(v))}">${esc(v.name)} · ${esc(v.lang)}${v.localService?' · 本机':' · 联网'}</option>`).join('');
  select.disabled=!list.length;
  select.value=voice&&(voiceKey(voice)===saved||(voice.voiceURI||voice.name)===saved)?voiceKey(voice):'';
  const message=!speechSupported?'此浏览器不支持朗读，请使用下方备用听音。':voice?`当前：${voice.name} · ${voice.lang}${voice.localService?' · 本机语音':' · 需要联网'}`:navigator.onLine?'暂未检测到德语语音：可重新检测，或使用下方备用听音。':'离线时未找到本机德语语音，请联网后重试。';
  status.textContent=message;
  $('#voice-test').disabled=!speechSupported;
  $('#voice-rate').value=String(speechRate());
  document.querySelectorAll('[data-voice-status]').forEach(el=>{el.textContent=voice?`${voice.name} · ${voice.lang}`:'选择德语声音 / 备用听音';});
}
function refreshVoices(){voices=speechSupported?speechSynthesis.getVoices().filter(v=>v&&v.lang).sort((a,b)=>voiceRank(b)-voiceRank(a)||a.name.localeCompare(b.name)):[];refreshVoiceSettings();return voices;}
function speechRate(){const rate=Number(get('pref|deRate',.85));return [.7,.85,1].includes(rate)?rate:.85;}
function stopSpeech(){currentUtterance=null;if(speechSupported)speechSynthesis.cancel();}
function openSettings(){refreshVoices();storageStatus();if(!$('#settings-dialog').open)$('#settings-dialog').showModal();}
function speak(text){
  stopSpeech();refreshVoices();
  $('#voice-fallback').href='https://translate.google.com/?sl=de&tl=en&text='+encodeURIComponent(text)+'&op=translate';
  const voice=preferredGermanVoice();
  if(!speechSupported||!voice){openSettings();toast('请选择德语声音，或用“备用听音”打开这段德语。');return;}
  const u=new SpeechSynthesisUtterance(text);
  u.voice=voice;u.lang=voice.lang.replace('_','-');u.rate=speechRate();u.pitch=1;
  currentUtterance=u;
  u.onend=()=>{if(currentUtterance===u)currentUtterance=null;};
  u.onerror=e=>{if(currentUtterance!==u)return;currentUtterance=null;if(!['interrupted','canceled'].includes(e.error)){openSettings();$('#voice-status').textContent='此声音暂时无法播放。请更换德语声音，或点击备用听音。';toast('朗读未成功，请更换声音或使用备用听音。');}};
  try{speechSynthesis.speak(u);}catch{currentUtterance=null;openSettings();toast('朗读未成功，请使用备用听音。');}
}
function timerKey(id){return `timer|${selectedDate}|${id}`;}
function updateTimer(id){const tick=()=>{let t=get(timerKey(id),null);if(!t)return;let remain=t.running?Math.max(0,Math.ceil((t.end-Date.now())/1000)):t.remaining;if(t.running&&remain===0){t={...t,running:false,remaining:0};put(timerKey(id),t);toast('朗读计时结束，请确认完成。');}if($('#timer-display'))$('#timer-display').textContent=`${String(Math.floor(remain/60)).padStart(2,'0')}:${String(remain%60).padStart(2,'0')}`;const b=main.querySelector('[data-action="timer-toggle"]');if(b)b.textContent=t.running?'暂停计时':remain===0?'重新开始':'继续计时';if($('#timer-duration')){$('#timer-duration').value=String(t.minutes);$('#timer-duration').disabled=t.running;}};tick();timerHandle=setInterval(tick,1000);}
main.addEventListener('input',e=>{const t=e.target;if(t.id==='search'){filter.q=t.value;updateSceneResults();}if(t.matches('[data-note]')){put(`note|${t.dataset.date}|${t.dataset.note}`,t.value);const s=$('#note-status');if(s)s.textContent=storageOK?`已自动保存 · ${t.value.trim().split(/\s+/).filter(Boolean).length} words`:'未保存：请导出备份';}});
main.addEventListener('change',e=>{const t=e.target;if(t.id==='scene-section'&&t.value){const el=document.getElementById(t.value);el?.scrollIntoView({block:'start'});el?.focus({preventScroll:true});}if(t.id==='category')filter.category=t.value;if(t.id==='scene-date')filter.date=t.value;if(t.id==='fav-filter')filter.favorite=t.checked;if(t.id==='unmastered-filter')filter.unmastered=t.checked;if(['category','scene-date','fav-filter','unmastered-filter'].includes(t.id))updateSceneResults();if(t.id==='german-only'){put('pref|germanOnly',t.checked);revealed.clear();render();}if(t.id==='study-date'){if(!validDay(t.value)||t.value<START||t.value>today){toast('请选择有效的过去或今日日期。');t.value=selectedDate;return;}selectedDate=t.value;const route=location.hash.split('/')[0];if(location.hash!==route)location.hash=route;else render();}if(t.matches('[data-step]')){if(t.dataset.step==='thinking'&&t.checked&&get(`note|${t.dataset.date}|${t.dataset.unit}`,'').trim().length<20){t.checked=false;toast('先写下至少一两句英文思考，再完成此项。');return;}put(stepKey(t.dataset.date,t.dataset.unit,t.dataset.step),t.checked);refreshUnitProgress(t.dataset.date,t.dataset.unit);toast(t.checked?'已记录完成':'已取消完成');}if(t.id==='timer-duration'){const id=location.hash.split('/')[1]||plan(selectedDate).lesson.id;put(timerKey(id),{remaining:Number(t.value)*60,minutes:Number(t.value),running:false});updateTimerDisplayOnly(id);}});
function updateTimerDisplayOnly(id){clearInterval(timerHandle);updateTimer(id);}
main.addEventListener('submit',e=>{if(e.target.id!=='quiz')return;e.preventDefault();const f=e.target,l=lessons.find(l=>l.id===f.dataset.unit),answers=l.quiz.map((_,i)=>Number(new FormData(f).get('q'+i))),score=l.quiz.filter((q,i)=>answers[i]===q[2]).length,result={answers,score};put(`quiz|${f.dataset.date}|${l.id}`,result);put(stepKey(f.dataset.date,l.id,'quiz'),score===3);$('#quiz-result').innerHTML=quizResult(l,result);refreshUnitProgress(f.dataset.date,l.id);});
main.addEventListener('click',e=>{if(e.target.closest('[data-featured]'))filter={q:'',category:'',date:'',favorite:false,unmastered:false};const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;if(a==='settings')openSettings();if(a==='clear-filters'){filter={q:'',category:'',date:'',favorite:false,unmastered:false};sceneList();}if(a==='clear-detail-filters'){filter={q:'',category:'',date:'',favorite:false,unmastered:false};render();}if(a==='reveal'){revealed.has(id)?revealed.delete(id):revealed.add(id);refreshPhrase(id);}if(a==='speak')speak(phraseMap.get(id).de);if(a==='speak-unit')speak(lessons.find(l=>l.id===id).input);if(a==='stop-speech')stopSpeech();if(a==='favorite'){put('favorite|'+id,!get('favorite|'+id));refreshPhrase(id);}if(a==='master'){const v=!get('mastered|'+id);put('mastered|'+id,v);put('due|'+id,dayShift(today,v?7:1));refreshPhrase(id);}if(a==='practice'){markPractice(id);toast('已记录今日自测，下次复习已安排。');}if(a==='refresh-review')review();if(a==='open-day'){selectedDate=b.dataset.date;const hash='#'+b.dataset.module;if(location.hash===hash)render();else location.hash=hash;}if(a==='timer-toggle'){let t=get(timerKey(id),null);const minutes=Number($('#timer-duration').value);if(!t||t.remaining===0)t={remaining:minutes*60,minutes,running:false};t=t.running?{...t,running:false,remaining:Math.max(0,Math.ceil((t.end-Date.now())/1000))}:{...t,running:true,end:Date.now()+t.remaining*1000};put(timerKey(id),t);updateTimerDisplayOnly(id);}if(a==='timer-reset'){const minutes=Number($('#timer-duration').value);put(timerKey(id),{remaining:minutes*60,minutes,running:false});updateTimerDisplayOnly(id);}});
$('#settings').onclick=openSettings;
$('#voice-select').onchange=e=>{stopSpeech();put('pref|deVoice',e.target.value);refreshVoiceSettings();toast(e.target.value?'已保存德语语音选择':'已恢复自动选择');};
$('#voice-test').onclick=()=>speak('Hallo. Ich möchte ein Buch bei Thalia abholen.');
$('#voice-rate').onchange=e=>{stopSpeech();put('pref|deRate',Number(e.target.value));};
$('#voice-refresh').onclick=refreshVoices;
$('#voice-stop').onclick=stopSpeech;
$('#settings-dialog').addEventListener('close',stopSpeech);
refreshVoices();
if(speechSupported){speechSynthesis.addEventListener('voiceschanged',refreshVoices);[250,1000,3000].forEach(ms=>setTimeout(refreshVoices,ms));}
$('#export').onclick=()=>{const data={...state,app:'Ning Learning',exportedAt:new Date().toISOString()},blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ning-learning-progress-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('进度备份已导出');};
function validateRecord(k,r){if(!r||typeof r!=='object'||!Number.isFinite(Date.parse(r.updated)))return false;const [type,a,b,c]=k.split('|');if(['favorite','mastered'].includes(type))return phraseMap.has(a)&&typeof r.value==='boolean';if(type==='due')return phraseMap.has(a)&&validDay(r.value);if(type==='pref'){if(a==='germanOnly')return typeof r.value==='boolean';if(a==='deVoice')return typeof r.value==='string'&&r.value.length<=1000;if(a==='deRate')return [.7,.85,1].includes(r.value);return false;}if(!validDay(a))return false;if(type==='practice')return phraseMap.has(b)&&typeof r.value==='boolean';const unit=[...lessons,...mba].find(u=>u.id===b);if(!unit)return false;if(type==='note')return typeof r.value==='string'&&r.value.length<=100000;if(type==='step')return stepsFor(b).includes(c)&&typeof r.value==='boolean';if(type==='quiz'){const v=r.value;return b.startsWith('de-')&&v&&Number.isInteger(v.score)&&v.score>=0&&v.score<=3&&Array.isArray(v.answers)&&v.answers.length===3&&v.answers.every(x=>Number.isInteger(x)&&x>=0&&x<=2);}if(type==='timer'){const v=r.value;return v&&[15,20,30].includes(v.minutes)&&typeof v.running==='boolean'&&Number.isFinite(v.remaining)&&v.remaining>=0&&v.remaining<=1800&&(!v.running||Number.isFinite(v.end));}return false;}
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error('文件过大');const incoming=JSON.parse(await file.text());if(incoming.version!==1||!incoming.records||typeof incoming.records!=='object'||Array.isArray(incoming.records))throw Error('不是兼容的备份');const entries=Object.entries(incoming.records);if(entries.some(([k,v])=>!validateRecord(k,v)))throw Error('备份含无效记录');try{localStorage.setItem(KEY+'-before-import',JSON.stringify(state));}catch{}for(const [k,v] of entries)if(!state.records[k]||v.updated>state.records[k].updated)state.records[k]=v;save();refreshVoices();render();toast('备份已合并，同一条记录保留更新版本。');}catch(err){toast('导入失败：'+err.message+'。原进度未更改。');}e.target.value='';};
addEventListener('hashchange',()=>{stopSpeech();render();window.scrollTo(0,0);main.focus({preventScroll:true});});
addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{const incoming=JSON.parse(e.newValue);if(incoming.version===1&&incoming.records){state=incoming;refreshVoices();render();}}catch{}}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&today!==localDate()){today=localDate();selectedDate=today;render();}});
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;$('#install').hidden=false;});$('#install').onclick=async()=>{if(installEvent){await installEvent.prompt();installEvent=null;$('#install').hidden=true;}};
function connection(){const e=$('#connection');e.textContent=navigator.onLine?'个人学习空间':'离线模式';}addEventListener('online',()=>{connection();refreshVoices();});addEventListener('offline',()=>{connection();refreshVoices();});connection();
if('serviceWorker'in navigator&&location.protocol!=='file:'){navigator.serviceWorker.register('./sw.js').catch(()=>{console.info('Offline cache unavailable.');});}
const context=document.modelContext;if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'ning_learning_progress',title:'读取 Ning 学习进度',description:'读取今日任务完成数、掌握句数和收藏句数。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({date:today,tasksCompleted:taskProgress(today).filter(Boolean).length,mastered:masteredCount(),favorites:favoriteCount()})})).catch(()=>{});}catch{}}
storageStatus();render();if(!storageOK)toast('无法读取已保存进度，请先检查备份。');
})();
